---
- name: Update Ubuntu
  hosts: all
  become: yes
  gather_facts: False
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      become_method: sudo
    
    - name: Upgrade all packages
      apt:
        upgrade: safe
        autoclean: yes
      become_method: sudo